export const ratingsArr = [
  {
    id: "r1",
    label: "Great Product",
    rating: 4,
    description: "I loved this product. It works well and is very efficient.",
    customerName: "John Doe",
    address: "123 Main Street, City, Country",
  },
  {
    id: "r2",
    label: "Excellent Service",
    rating: 5,
    description: "The service was exceptional. I highly recommend it!",
    customerName: "Alice Smith",
    address: "456 Elm Avenue, Town, Country",
  },
  {
    id: "r3",
    label: "Good Experience",
    rating: 3,
    description: "My experience was good, but there's room for improvement.",
    customerName: "Bob Johnson",
    address: "789 Oak Road, Village, Country",
  },
  {
    id: "r4",
    label: "Average",
    rating: 2,
    description: "It's just an average product, nothing special.",
    customerName: "Eva Brown",
    address: "101 Pine Lane, Hamlet, Country",
  },
  {
    id: "r5",
    label: "Terrible",
    rating: 1,
    description: "I had a terrible experience. Avoid at all costs!",
    customerName: "Chris Wilson",
    address: "202 Cedar Court, Settlement, Country",
  },
  {
    id: "r6",
    label: "Amazing Service",
    rating: 5,
    description: "The service provided was amazing. I couldn't be happier.",
    customerName: "Sophia Lee",
    address: "303 Maple Street, Town, Country",
  },
];
